import { supabase } from '../lib/supabase';
import { NewsItem, ShortItem, NewsType } from '../types';

export const api = {
    // --- NEWS ---
    async getNews() {
        const { data, error } = await supabase
            .from('news')
            .select('*')
            .order('timestamp', { ascending: false });

        if (error) throw error;

        return (data || []).map((item: any) => ({
            id: item.id,
            title: item.title,
            description: item.description,
            imageUrl: item.image_url,
            videoUrl: item.video_url,
            area: item.area,
            type: item.type as NewsType,
            isBreaking: item.is_breaking,
            timestamp: item.timestamp,
            author: item.author || 'Admin',
            status: item.status as 'published' | 'pending' | 'rejected'
        })) as NewsItem[];
    },

    async createNews(news: Omit<NewsItem, 'id' | 'timestamp'>) {
        const { data, error } = await supabase
            .from('news')
            .insert({
                title: news.title,
                description: news.description,
                image_url: news.imageUrl,
                video_url: news.videoUrl,
                area: news.area,
                type: news.type,
                is_breaking: news.isBreaking,
                author: news.author || 'Admin',
                status: news.status || 'published',
                // timestamp will be auto-generated by DB default
            })
            .select()
            .single();

        if (error) throw error;
        return data;
    },

    async updateNews(id: string, news: Partial<NewsItem>) {
        const updates: any = {};
        if (news.title !== undefined) updates.title = news.title;
        if (news.description !== undefined) updates.description = news.description;
        if (news.imageUrl !== undefined) updates.image_url = news.imageUrl;
        if (news.videoUrl !== undefined) updates.video_url = news.videoUrl;
        if (news.area !== undefined) updates.area = news.area;
        if (news.type !== undefined) updates.type = news.type;
        if (news.isBreaking !== undefined) updates.is_breaking = news.isBreaking;
        if (news.status !== undefined) updates.status = news.status;

        const { data, error } = await supabase
            .from('news')
            .update(updates)
            .eq('id', id)
            .select()
            .single();

        if (error) throw error;
        return data;
    },

    async deleteNews(id: string) {
        const { error } = await supabase
            .from('news')
            .delete()
            .eq('id', id);

        if (error) throw error;
    },

    // --- SHORTS ---
    async getShorts() {
        const { data, error } = await supabase
            .from('shorts')
            .select('*')
            .order('timestamp', { ascending: false });

        if (error) throw error;

        return (data || []).map((item: any) => ({
            id: item.id,
            title: item.title,
            videoUrl: item.video_url,
            duration: item.duration,
            timestamp: item.timestamp
        })) as ShortItem[];
    },

    async createShort(short: Omit<ShortItem, 'id' | 'timestamp'>) {
        const { data, error } = await supabase
            .from('shorts')
            .insert({
                title: short.title,
                video_url: short.videoUrl,
                duration: short.duration,
            })
            .select()
            .single();

        if (error) throw error;
        return data;
    },

    async updateShort(id: string, short: Partial<ShortItem>) {
        const updates: any = {};
        if (short.title !== undefined) updates.title = short.title;
        if (short.videoUrl !== undefined) updates.video_url = short.videoUrl;
        if (short.duration !== undefined) updates.duration = short.duration;

        const { data, error } = await supabase
            .from('shorts')
            .update(updates)
            .eq('id', id)
            .select()
            .single();

        if (error) throw error;
        return data;
    },

    async deleteShort(id: string) {
        const { error } = await supabase
            .from('shorts')
            .delete()
            .eq('id', id);

        if (error) throw error;
    },

    async uploadFile(file: File, bucket: 'news-media' = 'news-media') {
        console.log("Starting upload...", file.name, bucket);
        const fileExt = file.name.split('.').pop();
        const fileName = `${Date.now()}_${Math.random().toString(36).substring(7)}.${fileExt}`;
        const filePath = `${fileName}`;

        const { data, error } = await supabase.storage
            .from(bucket)
            .upload(filePath, file, {
                cacheControl: '3600',
                upsert: false,
                contentType: file.type // Explicitly set content type
            });

        if (error) {
            console.error("Supabase Upload Error:", error);
            throw error;
        }

        console.log("Upload successful, getting URL for:", filePath);
        const { data: { publicUrl } } = supabase.storage
            .from(bucket)
            .getPublicUrl(filePath);

        console.log("Public URL:", publicUrl);
        return publicUrl;
    }
};
